### ISSUE TITLE
[BUG] Submission not found if submissionName == file names

### ISSUE THREAD

**Issue by ezrichards** [CSCI128/128Autograder#77]
### Issue

If I have files tree (executable), tree.h, tree.c, no submissions will be found by the autograder.

### Steps to recreate

Make those files and set submission name = tree in config.toml.

### Solution

On Line 75 of CSubmission, don't check for a substring of the original string.

## Acceptance Criteria
- [ ] Fix it ;)

**Comment by gregbell26** [comment]
Adding to V4.0

**Comment by gregbell26** [comment]
Given that c support has been dropped, this will not be implemented.
