### ISSUE TITLE
[BUG] Incorrect input buffer size with subprocess

### ISSUE THREAD

**Issue by ezrichards** [CSCI128/128Autograder#78]
### Issue

Crazy Python subprocess piping thing.. see:
https://stackoverflow.com/questions/8475290/how-do-i-write-to-a-python-subprocess-stdin 
https://stackoverflow.com/questions/27571305/subprocess-stdin-buffer-not-flushing-on-newline-with-bufsize-1

### Steps to recreate

https://gist.github.com/ezrichards/9df42dea2bb21ec481690f577d579f1e
(let me know if code doesn't work, I redacted some of it from the answer key)

### Solution

sscanf and fgets _should_ be usable.

**Comment by gregbell26** [comment]
Adding to v4.0

**Comment by gregbell26** [comment]
Given that c support has been dropped, I am not going to implement this
